### ISSUE TITLE
Modify slashing mechanism

### ISSUE THREAD

**Issue by Logle** [BuildOnViction/tomochain-v1#353]
Following the current slashing design, https://medium.com/tomochain/tomochain-slashing-mechanism-for-network-stability-and-performance-cd7e7a9320f7, a Masternode will be slashed for the next 4 epochs, if she cannot sign any block in the current epoch. 

In practice, when a Masternode is down, it takes quite long to recover due to multiple factors (re-syncing time, VPS down etc.). Furthermore, a voter's stake will be locked for 96 epoch after unvoting which is much longer than the slashing time. Consequently, voters will have low incentive to unvote, and move to other Masternodes.

Propose: a Masternode will be slashed for the next 96 epochs, if cannot sign any block in the current epoch. This will also improve the consistency in the length of block's production if several groups of Masternodes are down.

**Comment by thanhson1085** [comment]
96 epochs seems too long, all voters of that masternode will be unvote that masternode. Becase the lock time for voter is 96 epochs too.

Actually, I concern more about 2 things:
- how to detect a bad masternode to slash it.
- how to detect a slashed node reach enough conditions to get back to Masternode Status

### how to detect a bad masternode to slash it
Currently, if a masternode does not create any "sign" Txs in an epoch will be get stashed. There are a technical issue here, the nodes have to execute a "for loop" in 900 blocks to calculate sign Txs numbers. That requires a lot of effort and time at checkpoint block.

I propose a solution that the node just need to executed a "for loop" in 5 blocks (e.g, 800 - 805) to calculate the sign Txs, if no "sign Txs" -> get slashed


### how to detect a slashed node reach enough conditions to get back to Masternode Status
Currently, a slashed masternode will get back to masternode automatically after slashed time (4 epochs). It is really bad if the masternode still in STOP status. Then the network will be slow down, becase a bad masternode get back.

I propose a solution that the node just need to executed a "for loop" in 5 blocks (e.g, 800 - 805) to calculate the sign Txs, if find 3 "sign Txs"/ 5 blocks -> get back to Masternode Status
So we will know the bad masternode is get back to normal status or not.

**Comment by etienne-napoleone** [comment]
Is there any way to require a masternode to be synced to being promoted as mn?
Would solve:
- ppl applying before being synced
- masternode who are still down or lagging behind to come back after slashing

If possible, this would maybe let us have the same or at least quite short slashing time I guess?

**Comment by khaihkd** [comment]
Be careful in this case. We only run MasterNode in 10 days, but we have 37 GB data. So in this future, a MasterNode need down time to mount more volume. Maybe in the first month data size is over 100GB

**Comment by etienne-napoleone** [comment]
> Be careful in this case. We only run MasterNode in 10 days, but we have 37 GB data. So in this future, a MasterNode need down time to mount more volume. Maybe in the first month data size is over 100GB

Yes might be a problem.
With DO volumes you can resize while running so 0 downtime, but most people might not be using them (or provider equivalent).

**Comment by Logle** [comment]
Better mechanisms like Son described would be good but need further analyses. Simply extending slashing time would be simple to do. Depending if we want a big modification or not.

**Comment by ambrosoni** [comment]
What about taking a piece of the above proposed solutions and make the slashing upgraded like this:
- Signed 0 blocks--> gets slashed like now without change (Some operators might find and fix issues really fast and we should be able to differentiated operators taking care and checking their nodes and those checking only ocasionally)
- If getting slashed for the second time right after the first (consecutively) slashing (didn't fix the issue fast enough or the solution simply takes more time) the time get longer and longer with every consecutive slash up to xx epochs without reward.. 
- Lets say one slash--> 4 epoch no rewards
- Second consecutive slash--> 16 epochs no reward
- Third consecutive slash--> 64 epochs no reward
- Fourth consecutive slash--> 96 epochs no reward

This way attentive operators will have an advantage over the others and one or two slashes (this doesn't even have to be their fault as the forked chain showed us) will not let them loose all the votes. They will be actually able to prove themselve.

**Comment by ambrosoni** [comment]
Another idea how to prune network and push epoch time closer to intented 30min.
I know release 1.2 will solve a lot of issues, but could we also possibly implement something like counter for not confirming blocks within epoch when node is chosen?
Lets say:
- Your node has been randomly chosen to confirm block, but for some reason didn't do so. If this scenario happens lets say 3-5 times within one epoch BOOM slashed for XX epoch
- That would of course only apply for synced nodes and online nodes. If  offline doing upgrade/update you only have to come back to confirm at least 1 block within epoch to not get slashed (Already working)
- Like that we would most likely have much less nodes, but only quality nodes and not nodes running under specified.
- This would actually prune network and push each epoch closer to 30 min.

Is something like this possible?

If let's say node slashed because it's stuck or some issue the above I mentioned could apply.

**Comment by ngtuna** [comment]
> Your node has been randomly chosen to confirm block, but for some reason didn't do so. If this scenario happens lets say 3-5 times within one epoch BOOM slashed for XX epoch

This is a good point.

**Comment by ngtuna** [comment]
That would be great to show the slashed history of masternode. Then the community can see which node has bad-performed frequently

**Comment by ngtuna** [comment]
Caching verifyPenalty will be implemented along with this.

**Comment by mohakagr** [comment]
I suggest to not put any additional penalty until the chain is stable. Currently, if the MN gets slashed it takes at least a few hours(not minutes) to get it up and running. 
If the technical issues can be resolved in the initial design and it can be implemented then that's the best design for now.

**Comment by ngtuna** [comment]
> I suggest to not put any additional penalty until the chain is stable. Currently, if the MN gets slashed it takes at least a few hours(not minutes) to get it up and running.
> If the technical issues can be resolved in the initial design and it can be implemented then that's the best design for now.

That's true. We keep improving the chain stability; that's the top priority atm. "Slashing 2.0" will only be implemented at v1.3 which is the next big release (hard-fork might be executed)

**Comment by ngtuna** [comment]
Summary from our last meeting which can be seen as final agreement on the slashing 2.0 policies:

- A mastenode will be tracked whether it's back to work or not after the period of 5 epochs slashed. The next 5 epochs will be applied in case it's still "offline"
- The conditions to validate working state of masternode is executed following suggestions from @thanhson1085 described above.
- There will be "slash history" info per each masternode displayed on TomoMaster which helps to define the good and bad masternodes.
-  Mastenodes take turn to create block. But for any reason a masternode who doesn't create any block which causes timeout 10 seconds will be slashed.

**Comment by ngtuna** [comment]
> Mastenodes take turn to create block. But for any reason a masternode who let's say X times doesn't create block which causes timeout 10 seconds will be slashed.

X = 3.
Count on both block producer (m1) and block validator (m2)

**Comment by mohakagr** [comment]
> * The conditions to validate working state of masternode is executed following suggestions from @thanhson1085 described above.
> * Mastenodes take turn to create block. But for any reason a masternode who let's say X times doesn't create block which causes timeout 10 seconds will be slashed.

This sounds great. The most important thing is when can a node get the masternode status again(after slashing) which is nicely addressed in the @thanhson1085's suggestions.

> * There will be "slash history" info per each masternode displayed on TomoMaster which helps to define the good and bad masternodes.

**One suggestion for showing the slash history:** Instead of showing a numerical number about how many times a node is slashed, please show some ratio(which includes the total epochs signed) which is fair to the early MNs as well as new MNs. As any fresh node or the node which joins the network at a late stage will have 0 or a smaller value under 'number of times slashed' versus the ones which have joined in early stages and was slashed due to challenges in the network instead of MN owners being lazy or using weak infrastructure.

**Comment by ambrosoni** [comment]
I have another idea for the slashing.
We implement the "if it's your turn to create block and you dont do so x=3 times you're slashed" but also if you don't confirm at lease 880 blocks per epoch you will be slashed as well. 
To become MN again you will need to prove that you are able to become MN again and not like now automatically MN after 4 epochs and than slowing down the chain by being still down. 
Here you would have to "sign- it will not be MN therefore not really signing" at least 880 blocks per epoch to become MN again. 
So possible scenario: You are slashed in epoch 4, because in epoch 3 you signed less than 880 blocks or you didnt create block for more than 3 times. If you fix your node in epoch 4 and make it ready to "sign- not really sign" at least 880 blocks in epoch 5, you will be back into MN in epoch 6.

If you fail to fix the node to be able to "sign" at least 880 blocks within epoch it will stay slashed- until it "signed" at least 880 block in the previous epoch.

This way you could actually support the vigilant MN owners by not prolonging the slash (4 epochs now even if fixed in 1 epoch) and still preserve the network from the bad nodes breaking the network.

After thinking about it we could lower the needed sign limit (lower than 880) so when doing "tmn update" or reboot of your instance you will not get slashed.

Feel free to use emoji if you like this idea.

**Comment by ngtuna** [comment]
@ambrosoni Thanks for the thoughts. 

> To become MN again you will need to prove that you are able to become MN again and not like now automatically MN after 4 epochs and than slowing down the chain by being still down.

It was mentioned at our final agreement above (point 1)

> Here you would have to "sign- it will not be MN therefore not really signing" at least 880 blocks per epoch to become MN again.
So possible scenario: You are slashed in epoch 4, because in epoch 3 you signed less than 880 blocks or you didnt create block for more than 3 times. If you fix your node in epoch 4 and make it ready to "sign- not really sign" at least 880 blocks in epoch 5, you will be back into MN in epoch 6.

In fact, masternodes are incentivized by reward which is measured via signing activity. Thus there is no reason for masternodes that are running but have no signatures at all. The less signs it makes, the less reward it receive. We count number of signatures of a masternode just to make sure it's coming back to work.

> If you fail to fix the node to be able to "sign" at least 880 blocks within epoch it will stay slashed- until it "signed" at least 880 block in the previous epoch.

That's a good idea. However it's a bit difficult from the implementation point of view considered the 2 secs block-time boundary. Counting signatures is sequential operation which consumes time in the linear manor. We don't want to increase block-time at the checkpoint. But we will consider this for further optimization.

**Comment by ngtuna** [comment]
closed via #451
