### ISSUE TITLE
SDK Fullnode panic

### ISSUE THREAD

**Issue by thanhnguyennguyen** [BuildOnViction/tomochain-v1#776]
Steps to reproduces:
- Point `ws_url` in SDK DEX configuration to websocket of fullnode
- Navigate to SDK UI, login with privatekey
-> SDK fullnode panic
![image](https://user-images.githubusercontent.com/17243442/67064290-30576b00-f194-11e9-893f-6b7f7115b3e3.png)

Note: everything is ok if we point `ws_url` to websocket of masternode

cc @pqv199x

**Comment by pqv199x** [comment]
A fullnode is not a masternode(cannot commit transaction), so it does not have enough configures such as coinbase address... to run some APIs.
1. Turn on AnnounceTxsFlag, `--announce-txs`, fullnode will try to commit tx as a masternode
Or:
2. Turn off option `Pending`(tomox-sdk):
```opts := &bind.CallOpts{Pending: true}```
when calling API. This changing will force API function get state of latest block number instead of pending block number(API throws errors if AnnounceTxsFlag is not set)

**Comment by thanhnguyennguyen** [comment]
thank Vu :bowing_man:
